[package]
name = "actix_web_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.7"
serde = { version = "1", features = ["derive"] }
rand = { version = "0.8", features = ["std", "alloc"] }
lazy_static = "1.4"
tokio = { version = "1", features = ["full"] }
